meta_product_name: "Groovy"
meta_title: "Groovy - Votre collection de vinyles sur mesure"
meta_description: "Collectionnez, organisez et échangez des vinyles pour obtenir la collection de vos rêves."
meta_image: "home-page.jpg" # should exist in `app/assets/images/`
